### ISSUE TITLE
vim gives exactly the same feature already !

### ISSUE THREAD

**Issue by dhruvagarwal** [Anmol-Singh-Jaggi/Directory-Snapshot#1]
Hey [Anmol Singh Jaggi](https://github.com/jaggi1234) , Well done on this project
I have a suggestion for you, just try doing 

```
        vim <directory_name>
```

It gives links same as you have done :)

But Well Done :+1:

**Comment by Anmol-Singh-Jaggi** [comment]
Oh ! nice.. I didn't know this. Anyways, that is more like a file explorer inside a terminal, which is not what this app is about. This app enables us to store a directory's information so that in case of a data loss, we are at least able to recollect what all was lost. For example, I have a folder of all the software I have ever downloaded from the Internet. Since I do not have a backup medium, I can atleast store its information on my online backup account ( which provides very little storage ), so that I will be able to download them again after a disk failure. Vim only works when all the data is still intact which defeats the very purpose of this app's idea !
